Traceback (most recent call last):
  File "/data/ephemeral/home/.GitHub/Lv.2-CV21/train.py", line 253, in <module>
    main(args)
  File "/data/ephemeral/home/.GitHub/Lv.2-CV21/train.py", line 247, in main
    do_training(args, **args.__dict__)
  File "/data/ephemeral/home/.GitHub/Lv.2-CV21/train.py", line 90, in do_training
    train_dataset = SceneTextDataset(
  File "/data/ephemeral/home/.GitHub/Lv.2-CV21/dataset.py", line 510, in __init__
    with open(os.path.join(root_dir, 'ufo/{}.json'.format(split)), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../dataset/ufo/train1.json'
